<#
.SYNOPSIS
    Wire the dashboard, FastAPI service, and ingestion scheduler to auto-start
    on logon. Generates VBS launchers IN the user's Startup folder with the
    absolute path to each repo .cmd file hardcoded - so the launcher works
    regardless of where the user originally cloned the repo from.

.EXAMPLE
    ./scripts/install-autostart.ps1
.EXAMPLE
    ./scripts/install-autostart.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [switch] $Uninstall
)

$ErrorActionPreference = "Stop"
$repo    = Split-Path -Parent $PSScriptRoot
$startup = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs\Startup"

$entries = @(
    @{ Vbs = "gridintel-api.vbs";       Cmd = (Join-Path $repo "scripts\start-api.cmd") }
    @{ Vbs = "gridintel-scheduler.vbs"; Cmd = (Join-Path $repo "scripts\start-scheduler.cmd") }
)

if ($Uninstall) {
    foreach ($e in $entries) {
        $dst = Join-Path $startup $e.Vbs
        if (Test-Path $dst) { Remove-Item -Force $dst; Write-Host "removed $dst" }
    }
    Write-Host "Auto-start uninstalled."
    return
}

# Sanity-check the .cmd files actually exist before we install launchers for them.
foreach ($e in $entries) {
    if (-not (Test-Path $e.Cmd)) { throw "Expected launcher not found: $($e.Cmd)" }
}

foreach ($e in $entries) {
    $dst = Join-Path $startup $e.Vbs
    # VBS string-doubled-quote escape for the path
    $escaped = $e.Cmd.Replace('"', '""')
    $vbsText = @"
' Auto-generated by grid-intelligence-platform\scripts\install-autostart.ps1
' Launches a repo .cmd file hidden so it runs in the background on logon.
Set ws = CreateObject("WScript.Shell")
ws.Run """$escaped""", 0, False
"@
    Set-Content -Path $dst -Value $vbsText -Encoding ascii
    Write-Host "installed $dst -> $($e.Cmd)"
}

# Kick them off now too, so the user doesn't have to log out / in.
foreach ($e in $entries) {
    Start-Process -FilePath "wscript.exe" -ArgumentList ("`"" + (Join-Path $startup $e.Vbs) + "`"") -WindowStyle Hidden
}
Write-Host ""
Write-Host "Both services launched."
Write-Host "  API       : http://127.0.0.1:8787   (/healthz, /docs)"
Write-Host "  Scheduler : ingests on cron - tail logs\scheduler.log"
